module.exports = {
    TestBusiness : require('./test.business'),
    PatientBusiness : require('./patient.business'),
    DoctorBusiness : require('./doctor.business'),
    MedicalHistoryBusiness : require('./medicalHistory.business'),
    UserBusiness : require('./user.business'),
    DeficitBusiness : require('./deficit.business'),
    DeseaseBusiness : require('./desease.business'),
    CategoryDeseaseBusiness : require('./categoryDesease.business'),
    MedicalConsultationBusiness : require('./medicalConsultation.business'),
    SymptomBusiness : require('./symptom.business'),
    CategoryDeseaseSymptomBusiness : require('./categoryDeseaseSymptom.business'),
    PrescriptionBusiness : require('./prescription.business'),
    QuestionBusiness : require('./question.business'),
    MonitoringBusiness : require('./monitoring.business'),
    ForoBusiness : require('./foro.business'),
}