module.exports = {
    TestService : require('./test.service'),
    PatientService : require('./patient.service'),
    DoctorService : require('./doctor.service'),
    MedicalHistoryService : require('./medicalHistory.service'),
    UserService : require('./user.service'),
    DeficitService : require('./deficit.service'),
    DeseaseService : require('./desease.service'),
    CategoryDeseaseService : require('./categoryDesease.service'),
    MedicalConsultationService : require('./medicalConsultation.service'),
    SymptomService : require('./symptom.service'),
    CategoryDeseaseSymptomService : require('./categoryDeseaseSymptom.service'),
    PrescriptionService : require('./prescription.service'),
    QuestionService : require('./question.service'),
    MonitoringService : require('./monitoring.service'),
    ForoService : require('./foro.service'),
}